<?php
include("banner.php");
include("profile.php");
include("skills.php");
include("resume.php");
include("services.php");
include("testimonials.php");
include("portfolio.php");
include("blog.php");
include("contact.php");
?>